description: A Mobile Blood Bank.
name: mobile_blood_bank
publish_to: "none"
version: 1.0.0+1

dependencies:
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  # flutter_native_splash: ^2.2.17
  # font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  http: ^0.13.4
  json_serializable: ^6.1.4
  lottie: ^1.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter:
  assets:
    - assets/animations/
    - assets/logo/
  uses-material-design: true
